### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by christyanbrayan** [christyanbrayan/js-cev#2]
- [ ] Incluir outros exercícios;
- [ ] Organizar estilos em um arquivo único
- [ ] Minificar arquivos e comprimir imagens na branch gh-pages;
- [ ] Incluir link pro GitHub no rodapé do index;
- [ ] Incluir licença [?];
